### ISSUE TITLE
Unclear what install procedure is

### ISSUE THREAD

**Issue by kreeuwijk** [domeger/SplunkTAforPuppetEnterprise#4]
I'm trying to get this SplunkTAforPuppetEnterprise app working, as well as the SplunkAppforPuppetEnterprise. I've been able to get the official 'Puppet Enterprise' app working, but not yet this one.

I have the following test setup:
- 1 Splunk Enterprise server, configured with a receiver on port 9997
- 1 Puppet Master, with a Spunk Universal Forwarder installed. It is forwarding to the Splunk Enterprise server, and it's also configured as a deployment client to the Splunk Enterprise deployment server

To get the 'Puppet Enterprise' app working, I added the app to $SPLUNK_HOME/etc/apps and $SPLUNK_HOME/etc/deployment-apps (both on the Splunk Enterprise server), and then used server classification to push the app to the Universal Forwarder as well. After a few minutes, data started coming in to the Splunk Enterprise server.

I've tried configuring the SplunkTAforPuppetEnterprise app (filling in the API key) via the Splunk Web UI, but the ./local/splunktaforpuppetenterprise_settings.conf file ends up looking like this:

[additional_parameters]
api_token = ********

[logging]
loglevel = INFO

Some questions:
- Is the API key getting mangled somewhere?
- Am I supposed to manually paste the API key into that file?
- Should I preconfigure the splunktaforpuppetenterprise_settings.conf file before copying the app to the deployment-apps folder?
- With the 1.0.7 version, I no longer see any inputs. Is this expected?
- What should be the recommended method of getting this up and running? Which app should I deploy where and how?

**Comment by domeger** [comment]
This app is not like the old version that was developed by Puppet a few years ago. This is completely API driven so no deployment server needed. This does not use the UF at all. The best way to get this Addon  working is by installed it on a HF (https://answers.splunk.com/answers/350273/how-to-set-up-a-heavy-forwarderdeployment-server-o-1.html) and generate a API key from the Puppet Master. You will also have to verify you can curl API calls from the HF. I took out of the inputs because it causing confusion and made it impossible to troubleshoot with customers who have never used Splunk before. The setup guide is located at this link. https://splunk.box.com/s/8buxwblhopu553cq03gamsys486mwyy0

**Comment by kreeuwijk** [comment]
OK for demo purposes I should be able to deploy the TA app on the my single Splunk Enterprise server as well I think? I've already enabled remote access to the PuppetDB API ports for that machine.
The guide is a great help, thank you for that and I will give it a try!

**Comment by kreeuwijk** [comment]
It's working well, thank you!
